[test]
levels = ["syntax", "install", "registration", "instantiation", "execution"]
publish = true

[test.workflows]
cpu = []
gpu = ['H3DPART-segment', 'H3DPART-segment-partgen']

[test.platforms]
linux = false
macos = false
windows = false
windows_portable = false
linux_gpu = true
windows_gpu = true
windows_portable_gpu = true
